apiVersion: v1
kind: ResourceQuota
metadata:
  name: github-pr-watcher
  namespace: dev
spec:
  hard:
    pods: "1"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values: ["github-pr-watcher"]
