// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/pr-reviewer/pkg/git"
)

type WorktreeManager struct {
	CreateWorktreeStub        func(context.Context, string, string, int) (string, error)
	createWorktreeMutex       sync.RWMutex
	createWorktreeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	createWorktreeReturns struct {
		result1 string
		result2 error
	}
	createWorktreeReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FetchStub        func(context.Context, string) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	fetchReturns struct {
		result1 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveWorktreeStub        func(context.Context, string, string) error
	removeWorktreeMutex       sync.RWMutex
	removeWorktreeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	removeWorktreeReturns struct {
		result1 error
	}
	removeWorktreeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WorktreeManager) CreateWorktree(arg1 context.Context, arg2 string, arg3 string, arg4 int) (string, error) {
	fake.createWorktreeMutex.Lock()
	ret, specificReturn := fake.createWorktreeReturnsOnCall[len(fake.createWorktreeArgsForCall)]
	fake.createWorktreeArgsForCall = append(fake.createWorktreeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateWorktreeStub
	fakeReturns := fake.createWorktreeReturns
	fake.recordInvocation("CreateWorktree", []interface{}{arg1, arg2, arg3, arg4})
	fake.createWorktreeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WorktreeManager) CreateWorktreeCallCount() int {
	fake.createWorktreeMutex.RLock()
	defer fake.createWorktreeMutex.RUnlock()
	return len(fake.createWorktreeArgsForCall)
}

func (fake *WorktreeManager) CreateWorktreeCalls(stub func(context.Context, string, string, int) (string, error)) {
	fake.createWorktreeMutex.Lock()
	defer fake.createWorktreeMutex.Unlock()
	fake.CreateWorktreeStub = stub
}

func (fake *WorktreeManager) CreateWorktreeArgsForCall(i int) (context.Context, string, string, int) {
	fake.createWorktreeMutex.RLock()
	defer fake.createWorktreeMutex.RUnlock()
	argsForCall := fake.createWorktreeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *WorktreeManager) CreateWorktreeReturns(result1 string, result2 error) {
	fake.createWorktreeMutex.Lock()
	defer fake.createWorktreeMutex.Unlock()
	fake.CreateWorktreeStub = nil
	fake.createWorktreeReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *WorktreeManager) CreateWorktreeReturnsOnCall(i int, result1 string, result2 error) {
	fake.createWorktreeMutex.Lock()
	defer fake.createWorktreeMutex.Unlock()
	fake.CreateWorktreeStub = nil
	if fake.createWorktreeReturnsOnCall == nil {
		fake.createWorktreeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createWorktreeReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *WorktreeManager) Fetch(arg1 context.Context, arg2 string) error {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Fetch", []interface{}{arg1, arg2})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorktreeManager) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *WorktreeManager) FetchCalls(stub func(context.Context, string) error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *WorktreeManager) FetchArgsForCall(i int) (context.Context, string) {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	argsForCall := fake.fetchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *WorktreeManager) FetchReturns(result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) FetchReturnsOnCall(i int, result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) RemoveWorktree(arg1 context.Context, arg2 string, arg3 string) error {
	fake.removeWorktreeMutex.Lock()
	ret, specificReturn := fake.removeWorktreeReturnsOnCall[len(fake.removeWorktreeArgsForCall)]
	fake.removeWorktreeArgsForCall = append(fake.removeWorktreeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RemoveWorktreeStub
	fakeReturns := fake.removeWorktreeReturns
	fake.recordInvocation("RemoveWorktree", []interface{}{arg1, arg2, arg3})
	fake.removeWorktreeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorktreeManager) RemoveWorktreeCallCount() int {
	fake.removeWorktreeMutex.RLock()
	defer fake.removeWorktreeMutex.RUnlock()
	return len(fake.removeWorktreeArgsForCall)
}

func (fake *WorktreeManager) RemoveWorktreeCalls(stub func(context.Context, string, string) error) {
	fake.removeWorktreeMutex.Lock()
	defer fake.removeWorktreeMutex.Unlock()
	fake.RemoveWorktreeStub = stub
}

func (fake *WorktreeManager) RemoveWorktreeArgsForCall(i int) (context.Context, string, string) {
	fake.removeWorktreeMutex.RLock()
	defer fake.removeWorktreeMutex.RUnlock()
	argsForCall := fake.removeWorktreeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *WorktreeManager) RemoveWorktreeReturns(result1 error) {
	fake.removeWorktreeMutex.Lock()
	defer fake.removeWorktreeMutex.Unlock()
	fake.RemoveWorktreeStub = nil
	fake.removeWorktreeReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) RemoveWorktreeReturnsOnCall(i int, result1 error) {
	fake.removeWorktreeMutex.Lock()
	defer fake.removeWorktreeMutex.Unlock()
	fake.RemoveWorktreeStub = nil
	if fake.removeWorktreeReturnsOnCall == nil {
		fake.removeWorktreeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeWorktreeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WorktreeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.WorktreeManager = new(WorktreeManager)
